language: go

go:
- 1.11.x

before_install:
  - sudo apt-get install -y dos2unix

deploy:
  provider: releases
  api_key:
    secure: gLqft+Hli5d2KfP2YUCT1VmiOFUuvxvcpXhkzY2CI3KKhGOEdSKNO1cyJFOlC0JCtz66AL3WyuXwlW/Gl+M92uK1ASdWgnGKXxI8b5TJgNSvE1QEwy+WlrlH4wmLefdEdVht5X5rD2ZcxK8HK6cLkp3ue/Mq+gd8DMlLqwp2vyFEE1nNQbUAArYsqqYRak4rGCD7FiSwtf0yfI1+Xt1LRpyq67Y04pO1rWX93xwkrNUngiUgo+eYvDkCQkOAA7lOWZomT87CyvTbcEjxWSw47zN6N8vXjlXfW9LQAH5MRUssGe7gpgcVWG5zuUDEVQcquvxWPU60mC51CCBjy2bOwmkbArgr3DzzufWvRS9jUzQJBBMgbcyJUlxSmuXr9Skrqqa1caf3P3bOMVwZlqGItSGKlEqqfXeX1vMqsEi8PM/r9mY73hL2xortqBe8YtD9wiYcPPxnzmYMsuP3hryzFdb1nzhWlHjXE/gYN5uWApKYFhMKDnxQXsppj9c9IUpeD9360yQKEbLoF67OP63r8hQ4fMvcl84RBNDQ2GcAaQgOTadGds9m3wNlHCgpJM0OXkv6PNOfwpInTvpLl5CaXmYd2hp8NCL10zcatezGsCB+A12o1GUNQKjsoIUqO5FJFPqNwxTLztIPbcFS2IO6Zue8lT1OKYFUGieut4P0eyQ=
  file:
    - intravatar-linux-amd64.tar.gz
    - intravatar-linux-arm.tar.gz
    - intravatar-darwin-amd64.tar.gz
    - intravatar-windows-amd64.zip
  on:
    tags: true
